# Generated by Django 5.0.6 on 2024-06-25 00:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="flan",
            name="flan_uuid",
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AddField(
            model_name="flan",
            name="is_private",
            field=models.BooleanField(default=False),
        ),
    ]
